version: "3.2"

services:
  rtorrent:
    image: lscr.io/linuxserver/rutorrent:latest
    env_file: /var/data/config/rtorrent/rtorrent.env
    volumes:
      - /var/data/media/:/media
      - /var/data/rtorrent:/config
    deploy:
      replicas: 1
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:rtorrent.example.com
        - traefik.port=80
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true            

        # traefikv2
        - "traefik.http.routers.rtorrent.rule=Host(`rtorrent.example.com`)"
        - "traefik.http.routers.rtorrent.entrypoints=https"
        - "traefik.http.services.rtorrent.loadbalancer.server.port=80"
        - "traefik.http.routers.rtorrent.middlewares=forward-auth"
    ports:
      - 36898:36898
    networks:
      - traefik_public
      - autopiratev2_public

networks:
  traefik_public:
    external: true
  autopiratev2_public:
    external: true