version: "3.2"

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    env_file: /var/data/config/lidarr/lidarr.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/data/media:/media
      - /var/data/lidarr:/config
    deploy:
      replicas: 1
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:lidarr.example.com
        - traefik.port=8686
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true        

        # traefikv2
        - "traefik.http.routers.lidarr.rule=Host(`lidarr.example.com`)"
        - "traefik.http.routers.lidarr.entrypoints=https"
        - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
        - "traefik.http.routers.lidarr.middlewares=forward-auth"
        
    networks:
      - traefik_public
      - autopiratev2_public

networks:
  traefik_public:
    external: true
  autopiratev2_public:
    external: true